# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/anulaciones.ui'
#
# Created: Sat Aug  7 13:55:17 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmAnulacionesFactura(object):
    def setupUi(self, frmAnulacionesFactura):
        frmAnulacionesFactura.setObjectName("frmAnulacionesFactura")
        frmAnulacionesFactura.resize(828, 645)
        frmAnulacionesFactura.setStyleSheet("None")
        self.centralwidget = QtGui.QWidget(frmAnulacionesFactura)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabdetails = QtGui.QWidget()
        self.tabdetails.setObjectName("tabdetails")
        self.gridLayout_2 = QtGui.QGridLayout(self.tabdetails)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.tabdetails)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtDocumentNumber = QtGui.QLineEdit(self.tabdetails)
        self.txtDocumentNumber.setEnabled(True)
        self.txtDocumentNumber.setReadOnly(True)
        self.txtDocumentNumber.setObjectName("txtDocumentNumber")
        self.gridLayout_2.addWidget(self.txtDocumentNumber, 0, 1, 1, 1)
        self.tabledetails = QtGui.QTableView(self.tabdetails)
        self.tabledetails.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabledetails.sizePolicy().hasHeightForWidth())
        self.tabledetails.setSizePolicy(sizePolicy)
        self.tabledetails.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tabledetails.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabledetails.setAlternatingRowColors(True)
        self.tabledetails.setSortingEnabled(True)
        self.tabledetails.setObjectName("tabledetails")
        self.tabledetails.horizontalHeader().setStretchLastSection(True)
        self.tabledetails.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.tabledetails, 3, 0, 1, 7)
        self.groupBox_2 = QtGui.QGroupBox(self.tabdetails)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txtObservations = QtGui.QPlainTextEdit(self.groupBox_2)
        self.txtObservations.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtObservations.sizePolicy().hasHeightForWidth())
        self.txtObservations.setSizePolicy(sizePolicy)
        self.txtObservations.setReadOnly(True)
        self.txtObservations.setObjectName("txtObservations")
        self.gridLayout_3.addWidget(self.txtObservations, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 4, 0, 1, 5)
        self.groupBox = QtGui.QGroupBox(self.tabdetails)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lblSubtotal = QtGui.QLabel(self.groupBox)
        self.lblSubtotal.setObjectName("lblSubtotal")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblSubtotal)
        self.label_8 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lblIVA = QtGui.QLabel(self.groupBox)
        self.lblIVA.setObjectName("lblIVA")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lblIVA)
        self.label_11 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.lblTotal = QtGui.QLabel(self.groupBox)
        self.lblTotal.setObjectName("lblTotal")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lblTotal)
        self.label_5 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lblTotalD = QtGui.QLabel(self.groupBox)
        self.lblTotalD.setObjectName("lblTotalD")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lblTotalD)
        self.gridLayout_2.addWidget(self.groupBox, 4, 5, 1, 2)
        self.label_3 = QtGui.QLabel(self.tabdetails)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.swProvider = QtGui.QStackedWidget(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swProvider.sizePolicy().hasHeightForWidth())
        self.swProvider.setSizePolicy(sizePolicy)
        self.swProvider.setObjectName("swProvider")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbProvider = QtGui.QComboBox(self.page)
        self.cbProvider.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbProvider.sizePolicy().hasHeightForWidth())
        self.cbProvider.setSizePolicy(sizePolicy)
        self.cbProvider.setEditable(True)
        self.cbProvider.setObjectName("cbProvider")
        self.horizontalLayout_2.addWidget(self.cbProvider)
        self.swProvider.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.txtProvider = QtGui.QLineEdit(self.page_2)
        self.txtProvider.setEnabled(True)
        self.txtProvider.setReadOnly(True)
        self.txtProvider.setObjectName("txtProvider")
        self.horizontalLayout_5.addWidget(self.txtProvider)
        self.swProvider.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.swProvider, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tabdetails)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.txtnfactura = QtGui.QLineEdit(self.tabdetails)
        self.txtnfactura.setReadOnly(True)
        self.txtnfactura.setObjectName("txtnfactura")
        self.gridLayout_2.addWidget(self.txtnfactura, 2, 1, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/document-edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabdetails, icon, "")
        self.tabnavigation = QtGui.QWidget()
        self.tabnavigation.setObjectName("tabnavigation")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabnavigation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tablenavigation = QtGui.QTableView(self.tabnavigation)
        self.tablenavigation.setAlternatingRowColors(True)
        self.tablenavigation.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablenavigation.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablenavigation.setObjectName("tablenavigation")
        self.tablenavigation.horizontalHeader().setStretchLastSection(True)
        self.tablenavigation.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tablenavigation)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtGui.QLabel(self.tabnavigation)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.txtSearch = QtGui.QLineEdit(self.tabnavigation)
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout.addWidget(self.txtSearch)
        self.verticalLayout.addLayout(self.horizontalLayout)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabnavigation, icon1, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        frmAnulacionesFactura.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(frmAnulacionesFactura)
        self.statusbar.setObjectName("statusbar")
        frmAnulacionesFactura.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(frmAnulacionesFactura)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        frmAnulacionesFactura.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionNew = QtGui.QAction(frmAnulacionesFactura)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon2)
        self.actionNew.setObjectName("actionNew")
        self.actionPreview = QtGui.QAction(frmAnulacionesFactura)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/document-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreview.setIcon(icon3)
        self.actionPreview.setObjectName("actionPreview")
        self.actionGoFirst = QtGui.QAction(frmAnulacionesFactura)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res/go-first.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGoFirst.setIcon(icon4)
        self.actionGoFirst.setObjectName("actionGoFirst")
        self.actionGoPrevious = QtGui.QAction(frmAnulacionesFactura)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/res/go-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGoPrevious.setIcon(icon5)
        self.actionGoPrevious.setObjectName("actionGoPrevious")
        self.actionGoNext = QtGui.QAction(frmAnulacionesFactura)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/res/go-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGoNext.setIcon(icon6)
        self.actionGoNext.setObjectName("actionGoNext")
        self.actionGoLast = QtGui.QAction(frmAnulacionesFactura)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/res/go-last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGoLast.setIcon(icon7)
        self.actionGoLast.setObjectName("actionGoLast")
        self.actionSave = QtGui.QAction(frmAnulacionesFactura)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/res/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon8)
        self.actionSave.setVisible(False)
        self.actionSave.setObjectName("actionSave")
        self.actionCancel = QtGui.QAction(frmAnulacionesFactura)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/res/dialog-cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCancel.setIcon(icon9)
        self.actionCancel.setVisible(False)
        self.actionCancel.setObjectName("actionCancel")
        self.actionDeleteRow = QtGui.QAction(frmAnulacionesFactura)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/res/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteRow.setIcon(icon10)
        self.actionDeleteRow.setObjectName("actionDeleteRow")
        self.actionEditCell = QtGui.QAction(frmAnulacionesFactura)
        self.actionEditCell.setIcon(icon)
        self.actionEditCell.setObjectName("actionEditCell")
        self.actionCopy = QtGui.QAction(frmAnulacionesFactura)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/res/edit-copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon11)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtGui.QAction(frmAnulacionesFactura)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/res/edit-cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon12)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtGui.QAction(frmAnulacionesFactura)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/res/edit-paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon13)
        self.actionPaste.setObjectName("actionPaste")
        self.actionRefresh = QtGui.QAction(frmAnulacionesFactura)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/res/view-refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon14)
        self.actionRefresh.setVisible(False)
        self.actionRefresh.setObjectName("actionRefresh")
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addAction(self.actionCancel)
        self.toolBar.addAction(self.actionPreview)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGoFirst)
        self.toolBar.addAction(self.actionGoPrevious)
        self.toolBar.addAction(self.actionGoNext)
        self.toolBar.addAction(self.actionGoLast)
        self.label_4.setBuddy(self.txtSearch)

        self.retranslateUi(frmAnulacionesFactura)
        self.tabWidget.setCurrentIndex(0)
        self.swProvider.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(frmAnulacionesFactura)
        frmAnulacionesFactura.setTabOrder(self.txtDocumentNumber, self.txtProvider)
        frmAnulacionesFactura.setTabOrder(self.txtProvider, self.tabledetails)
        frmAnulacionesFactura.setTabOrder(self.tabledetails, self.txtObservations)
        frmAnulacionesFactura.setTabOrder(self.txtObservations, self.tabWidget)
        frmAnulacionesFactura.setTabOrder(self.tabWidget, self.cbProvider)
        frmAnulacionesFactura.setTabOrder(self.cbProvider, self.tablenavigation)
        frmAnulacionesFactura.setTabOrder(self.tablenavigation, self.txtSearch)

    def retranslateUi(self, frmAnulacionesFactura):
        frmAnulacionesFactura.setWindowTitle(QtGui.QApplication.translate("frmAnulacionesFactura", "Anulacion de Factura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "# Anulacion", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmAnulacionesFactura", "Observaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Subtotal: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSubtotal.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "IVA: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIVA.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Total: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTotal.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Total D", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTotalD.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "# Factura", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabdetails), None)
        self.label_4.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "&Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabnavigation), None)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("frmAnulacionesFactura", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Nuevo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("frmAnulacionesFactura", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreview.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Previsualizar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoFirst.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Ir al Primer Registro", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoPrevious.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Ir al Registro Anterior", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoNext.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Ir al siguiente registro", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoLast.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Ir al ultimo registro", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("frmAnulacionesFactura", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCancel.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeleteRow.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Borrar Fila", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeleteRow.setShortcut(QtGui.QApplication.translate("frmAnulacionesFactura", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditCell.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Editar Celda", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditCell.setShortcut(QtGui.QApplication.translate("frmAnulacionesFactura", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Copiar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("frmAnulacionesFactura", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Cortar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Pegar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("frmAnulacionesFactura", "Actualizar", None, QtGui.QApplication.UnicodeUTF8))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    frmAnulacionesFactura = QtGui.QMainWindow()
    ui = Ui_frmAnulacionesFactura()
    ui.setupUi(frmAnulacionesFactura)
    frmAnulacionesFactura.show()
    sys.exit(app.exec_())

