# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\workspace\EsquipulasPy\src\ui\frmApertura.ui'
#
# Created: Thu Aug 12 15:12:05 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmApertura(object):
    def setupUi(self, frmApertura):
        frmApertura.setObjectName("frmApertura")
        frmApertura.setWindowModality(QtCore.Qt.ApplicationModal)
        frmApertura.resize(216, 250)
        self.gridLayout = QtGui.QGridLayout(frmApertura)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtGui.QLabel(frmApertura)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.txtUsuario = QtGui.QLineEdit(frmApertura)
        self.txtUsuario.setReadOnly(False)
        self.txtUsuario.setObjectName("txtUsuario")
        self.gridLayout.addWidget(self.txtUsuario, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(frmApertura)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.dtFechaTime = QtGui.QDateTimeEdit(frmApertura)
        self.dtFechaTime.setCalendarPopup(True)
        self.dtFechaTime.setObjectName("dtFechaTime")
        self.gridLayout.addWidget(self.dtFechaTime, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(frmApertura)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.swcaja = QtGui.QStackedWidget(frmApertura)
        self.swcaja.setMaximumSize(QtCore.QSize(16777215, 200))
        self.swcaja.setObjectName("swcaja")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbcaja = QtGui.QComboBox(self.page)
        self.cbcaja.setObjectName("cbcaja")
        self.horizontalLayout.addWidget(self.cbcaja)
        self.swcaja.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtcaja = QtGui.QLineEdit(self.page_2)
        self.txtcaja.setReadOnly(False)
        self.txtcaja.setObjectName("txtcaja")
        self.horizontalLayout_2.addWidget(self.txtcaja)
        self.swcaja.addWidget(self.page_2)
        self.horizontalLayout_3.addWidget(self.swcaja)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.label_2 = QtGui.QLabel(frmApertura)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.txtMonto = QtGui.QDoubleSpinBox(frmApertura)
        self.txtMonto.setDecimals(4)
        self.txtMonto.setMaximum(1000000000.0)
        self.txtMonto.setObjectName("txtMonto")
        self.gridLayout.addWidget(self.txtMonto, 3, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(frmApertura)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.txtUser = QtGui.QLineEdit(self.groupBox)
        self.txtUser.setReadOnly(False)
        self.txtUser.setObjectName("txtUser")
        self.gridLayout_2.addWidget(self.txtUser, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.txtPassword = QtGui.QLineEdit(self.groupBox)
        self.txtPassword.setReadOnly(False)
        self.txtPassword.setObjectName("txtPassword")
        self.gridLayout_2.addWidget(self.txtPassword, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 4, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(frmApertura)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 1, 1, 1)

        self.retranslateUi(frmApertura)
        self.swcaja.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), frmApertura.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), frmApertura.reject)
        QtCore.QMetaObject.connectSlotsByName(frmApertura)
        frmApertura.setTabOrder(self.txtUsuario, self.dtFechaTime)
        frmApertura.setTabOrder(self.dtFechaTime, self.cbcaja)
        frmApertura.setTabOrder(self.cbcaja, self.txtMonto)
        frmApertura.setTabOrder(self.txtMonto, self.buttonBox)

    def retranslateUi(self, frmApertura):
        frmApertura.setWindowTitle(QtGui.QApplication.translate("frmApertura", "Apertura de Caja", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("frmApertura", "Cajero:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmApertura", "Fecha", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmApertura", "Caja", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmApertura", "Monto", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmApertura", "Autorizacion Por:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("frmApertura", "Usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("frmApertura", "Contraseña", None, QtGui.QApplication.UnicodeUTF8))

