# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/frmmovimientosbancarios.ui'
#
# Created: Mon Aug 23 03:31:45 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmMovimientosBancarios(object):
    def setupUi(self, frmMovimientosBancarios):
        frmMovimientosBancarios.setObjectName("frmMovimientosBancarios")
        frmMovimientosBancarios.resize(531, 517)
        frmMovimientosBancarios.setMinimumSize(QtCore.QSize(0, 40))
        self.centralwidget = QtGui.QWidget(frmMovimientosBancarios)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tabdetails = QtGui.QWidget()
        self.tabdetails.setObjectName("tabdetails")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabdetails)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_27 = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_5.addWidget(self.label_27)
        self.swcuenta = QtGui.QStackedWidget(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swcuenta.sizePolicy().hasHeightForWidth())
        self.swcuenta.setSizePolicy(sizePolicy)
        self.swcuenta.setMinimumSize(QtCore.QSize(0, 40))
        self.swcuenta.setObjectName("swcuenta")
        self.page_17 = QtGui.QWidget()
        self.page_17.setObjectName("page_17")
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.page_17)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.swcuenta.addWidget(self.page_17)
        self.page_18 = QtGui.QWidget()
        self.page_18.setObjectName("page_18")
        self.horizontalLayout_33 = QtGui.QHBoxLayout(self.page_18)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.txtcuenta = QtGui.QLineEdit(self.page_18)
        self.txtcuenta.setAlignment(QtCore.Qt.AlignCenter)
        self.txtcuenta.setReadOnly(True)
        self.txtcuenta.setObjectName("txtcuenta")
        self.horizontalLayout_33.addWidget(self.txtcuenta)
        self.swcuenta.addWidget(self.page_18)
        self.horizontalLayout_5.addWidget(self.swcuenta)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_25 = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        self.swtipodoc = QtGui.QStackedWidget(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swtipodoc.sizePolicy().hasHeightForWidth())
        self.swtipodoc.setSizePolicy(sizePolicy)
        self.swtipodoc.setMinimumSize(QtCore.QSize(0, 40))
        self.swtipodoc.setMaximumSize(QtCore.QSize(16777215, 30))
        self.swtipodoc.setObjectName("swtipodoc")
        self.page_19 = QtGui.QWidget()
        self.page_19.setObjectName("page_19")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_19)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cbtipodoc = QtGui.QComboBox(self.page_19)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbtipodoc.sizePolicy().hasHeightForWidth())
        self.cbtipodoc.setSizePolicy(sizePolicy)
        self.cbtipodoc.setEditable(True)
        self.cbtipodoc.setObjectName("cbtipodoc")
        self.verticalLayout_3.addWidget(self.cbtipodoc)
        self.swtipodoc.addWidget(self.page_19)
        self.page_20 = QtGui.QWidget()
        self.page_20.setObjectName("page_20")
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.page_20)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.txttipodoc = QtGui.QLineEdit(self.page_20)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txttipodoc.sizePolicy().hasHeightForWidth())
        self.txttipodoc.setSizePolicy(sizePolicy)
        self.txttipodoc.setMinimumSize(QtCore.QSize(0, 20))
        self.txttipodoc.setStyleSheet("None")
        self.txttipodoc.setDragEnabled(True)
        self.txttipodoc.setReadOnly(True)
        self.txttipodoc.setObjectName("txttipodoc")
        self.horizontalLayout_30.addWidget(self.txttipodoc)
        self.swtipodoc.addWidget(self.page_20)
        self.horizontalLayout_4.addWidget(self.swtipodoc)
        self.label_26 = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_4.addWidget(self.label_26)
        self.dtPicker = QtGui.QDateTimeEdit(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtPicker.sizePolicy().hasHeightForWidth())
        self.dtPicker.setSizePolicy(sizePolicy)
        self.dtPicker.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dtPicker.setReadOnly(False)
        self.dtPicker.setCalendarPopup(True)
        self.dtPicker.setObjectName("dtPicker")
        self.horizontalLayout_4.addWidget(self.dtPicker)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_23 = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_28.addWidget(self.label_23)
        self.swconcepto = QtGui.QStackedWidget(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swconcepto.sizePolicy().hasHeightForWidth())
        self.swconcepto.setSizePolicy(sizePolicy)
        self.swconcepto.setMaximumSize(QtCore.QSize(16777215, 30))
        self.swconcepto.setObjectName("swconcepto")
        self.page_15 = QtGui.QWidget()
        self.page_15.setObjectName("page_15")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.page_15)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.cbconcepto = QtGui.QComboBox(self.page_15)
        self.cbconcepto.setMinimumSize(QtCore.QSize(0, 20))
        self.cbconcepto.setEditable(True)
        self.cbconcepto.setObjectName("cbconcepto")
        self.verticalLayout_12.addWidget(self.cbconcepto)
        self.swconcepto.addWidget(self.page_15)
        self.page_16 = QtGui.QWidget()
        self.page_16.setObjectName("page_16")
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.page_16)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.txtconcepto = QtGui.QLineEdit(self.page_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtconcepto.sizePolicy().hasHeightForWidth())
        self.txtconcepto.setSizePolicy(sizePolicy)
        self.txtconcepto.setMinimumSize(QtCore.QSize(0, 20))
        self.txtconcepto.setStyleSheet("None")
        self.txtconcepto.setDragEnabled(True)
        self.txtconcepto.setReadOnly(True)
        self.txtconcepto.setObjectName("txtconcepto")
        self.horizontalLayout_29.addWidget(self.txtconcepto)
        self.swconcepto.addWidget(self.page_16)
        self.horizontalLayout_28.addWidget(self.swconcepto)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.label_22 = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.splitter = QtGui.QSplitter(self.tabdetails)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabledetails = QtGui.QTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabledetails.sizePolicy().hasHeightForWidth())
        self.tabledetails.setSizePolicy(sizePolicy)
        self.tabledetails.setMinimumSize(QtCore.QSize(300, 100))
        self.tabledetails.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabledetails.setObjectName("tabledetails")
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtobservaciones = QtGui.QTextEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtobservaciones.sizePolicy().hasHeightForWidth())
        self.txtobservaciones.setSizePolicy(sizePolicy)
        self.txtobservaciones.setMinimumSize(QtCore.QSize(0, 40))
        self.txtobservaciones.setObjectName("txtobservaciones")
        self.horizontalLayout_2.addWidget(self.txtobservaciones)
        self.verticalLayout.addWidget(self.splitter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/document-edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabdetails, icon, "")
        self.tabnavigation = QtGui.QWidget()
        self.tabnavigation.setObjectName("tabnavigation")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabnavigation)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tablenavigation = QtGui.QTableView(self.tabnavigation)
        self.tablenavigation.setAlternatingRowColors(True)
        self.tablenavigation.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablenavigation.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablenavigation.setObjectName("tablenavigation")
        self.tablenavigation.horizontalHeader().setStretchLastSection(True)
        self.tablenavigation.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tablenavigation)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtGui.QLabel(self.tabnavigation)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.txtSearch = QtGui.QLineEdit(self.tabnavigation)
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout.addWidget(self.txtSearch)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabnavigation, icon1, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        frmMovimientosBancarios.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(frmMovimientosBancarios)
        self.statusbar.setObjectName("statusbar")
        frmMovimientosBancarios.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(frmMovimientosBancarios)
        self.toolBar.setObjectName("toolBar")
        frmMovimientosBancarios.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.label_27.setBuddy(self.txtcuenta)
        self.label_26.setBuddy(self.dtPicker)
        self.label_23.setBuddy(self.txtconcepto)
        self.label_4.setBuddy(self.txtSearch)

        self.retranslateUi(frmMovimientosBancarios)
        self.tabWidget.setCurrentIndex(1)
        self.swcuenta.setCurrentIndex(1)
        self.swtipodoc.setCurrentIndex(0)
        self.cbtipodoc.setCurrentIndex(-1)
        self.swconcepto.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMovimientosBancarios)
        frmMovimientosBancarios.setTabOrder(self.tabWidget, self.tablenavigation)
        frmMovimientosBancarios.setTabOrder(self.tablenavigation, self.txtSearch)

    def retranslateUi(self, frmMovimientosBancarios):
        frmMovimientosBancarios.setWindowTitle(QtGui.QApplication.translate("frmMovimientosBancarios", "Movimientos Contables", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("frmMovimientosBancarios", "Cuenta Bancaria", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("frmMovimientosBancarios", "Tipo de Doc.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("frmMovimientosBancarios", "Fecha", None, QtGui.QApplication.UnicodeUTF8))
        self.dtPicker.setDisplayFormat(QtGui.QApplication.translate("frmMovimientosBancarios", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("frmMovimientosBancarios", "En concepto de:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("frmMovimientosBancarios", "Cuentas que afecta", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmMovimientosBancarios", "Observaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabdetails), None)
        self.label_4.setText(QtGui.QApplication.translate("frmMovimientosBancarios", "&Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabnavigation), None)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("frmMovimientosBancarios", "toolBar", None, QtGui.QApplication.UnicodeUTF8))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    frmMovimientosBancarios = QtGui.QMainWindow()
    ui = Ui_frmMovimientosBancarios()
    ui.setupUi(frmMovimientosBancarios)
    frmMovimientosBancarios.show()
    sys.exit(app.exec_())

