# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/marcos/workspace/EsquipulasPy/src/ui/mainwindowcontabilidad.ui'
#
# Created: Fri Jul 23 19:49:24 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1151, 753)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setViewMode(QtGui.QMdiArea.TabbedView)
        self.mdiArea.setTabShape(QtGui.QTabWidget.Rounded)
        self.mdiArea.setTabPosition(QtGui.QTabWidget.North)
        self.mdiArea.setObjectName("mdiArea")
        self.horizontalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(230, 156))
        self.dockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtGui.QToolBox(self.dockWidgetContents_2)
        self.toolBox.setObjectName("toolBox")
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 274, 626))
        self.page_2.setObjectName("page_2")
        self.gridLayout = QtGui.QGridLayout(self.page_2)
        self.gridLayout.setObjectName("gridLayout")
        self.btnConceptos = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConceptos.sizePolicy().hasHeightForWidth())
        self.btnConceptos.setSizePolicy(sizePolicy)
        self.btnConceptos.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnConceptos.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/res/view-pim-tasks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConceptos.setIcon(icon1)
        self.btnConceptos.setIconSize(QtCore.QSize(48, 48))
        self.btnConceptos.setAutoDefault(False)
        self.btnConceptos.setDefault(False)
        self.btnConceptos.setFlat(False)
        self.btnConceptos.setObjectName("btnConceptos")
        self.gridLayout.addWidget(self.btnConceptos, 0, 0, 1, 1)
        self.btnBalance = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBalance.sizePolicy().hasHeightForWidth())
        self.btnBalance.setSizePolicy(sizePolicy)
        self.btnBalance.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnBalance.setFont(font)
        self.btnBalance.setIcon(icon1)
        self.btnBalance.setIconSize(QtCore.QSize(48, 48))
        self.btnBalance.setAutoDefault(False)
        self.btnBalance.setDefault(False)
        self.btnBalance.setFlat(False)
        self.btnBalance.setObjectName("btnBalance")
        self.gridLayout.addWidget(self.btnBalance, 1, 0, 1, 1)
        self.btnEstado = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEstado.sizePolicy().hasHeightForWidth())
        self.btnEstado.setSizePolicy(sizePolicy)
        self.btnEstado.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnEstado.setFont(font)
        self.btnEstado.setIcon(icon1)
        self.btnEstado.setIconSize(QtCore.QSize(48, 48))
        self.btnEstado.setAutoDefault(False)
        self.btnEstado.setDefault(False)
        self.btnEstado.setFlat(False)
        self.btnEstado.setObjectName("btnEstado")
        self.gridLayout.addWidget(self.btnEstado, 2, 0, 1, 1)
        self.btnMovements = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMovements.sizePolicy().hasHeightForWidth())
        self.btnMovements.setSizePolicy(sizePolicy)
        self.btnMovements.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnMovements.setFont(font)
        self.btnMovements.setIcon(icon1)
        self.btnMovements.setIconSize(QtCore.QSize(48, 48))
        self.btnMovements.setAutoDefault(False)
        self.btnMovements.setDefault(False)
        self.btnMovements.setFlat(False)
        self.btnMovements.setObjectName("btnMovements")
        self.gridLayout.addWidget(self.btnMovements, 3, 0, 1, 1)
        self.btnAccounts = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAccounts.sizePolicy().hasHeightForWidth())
        self.btnAccounts.setSizePolicy(sizePolicy)
        self.btnAccounts.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnAccounts.setFont(font)
        self.btnAccounts.setIcon(icon1)
        self.btnAccounts.setIconSize(QtCore.QSize(48, 48))
        self.btnAccounts.setAutoDefault(False)
        self.btnAccounts.setDefault(False)
        self.btnAccounts.setFlat(False)
        self.btnAccounts.setObjectName("btnAccounts")
        self.gridLayout.addWidget(self.btnAccounts, 4, 0, 1, 1)
        self.btnConciliacion = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConciliacion.sizePolicy().hasHeightForWidth())
        self.btnConciliacion.setSizePolicy(sizePolicy)
        self.btnConciliacion.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnConciliacion.setFont(font)
        self.btnConciliacion.setIcon(icon1)
        self.btnConciliacion.setIconSize(QtCore.QSize(48, 48))
        self.btnConciliacion.setAutoDefault(False)
        self.btnConciliacion.setDefault(False)
        self.btnConciliacion.setFlat(False)
        self.btnConciliacion.setObjectName("btnConciliacion")
        self.gridLayout.addWidget(self.btnConciliacion, 5, 0, 1, 1)
        self.btnNotasCD = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNotasCD.sizePolicy().hasHeightForWidth())
        self.btnNotasCD.setSizePolicy(sizePolicy)
        self.btnNotasCD.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnNotasCD.setFont(font)
        self.btnNotasCD.setIcon(icon1)
        self.btnNotasCD.setIconSize(QtCore.QSize(48, 48))
        self.btnNotasCD.setAutoDefault(False)
        self.btnNotasCD.setDefault(False)
        self.btnNotasCD.setFlat(False)
        self.btnNotasCD.setObjectName("btnNotasCD")
        self.gridLayout.addWidget(self.btnNotasCD, 6, 0, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.dockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionLockSession = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/object-locked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLockSession.setIcon(icon2)
        self.actionLockSession.setObjectName("actionLockSession")
        self.actionUnlockSession = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/object-unlocked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnlockSession.setIcon(icon3)
        self.actionUnlockSession.setVisible(False)
        self.actionUnlockSession.setObjectName("actionUnlockSession")
        self.toolBar.addAction(self.actionLockSession)
        self.toolBar.addAction(self.actionUnlockSession)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Llantera Esquipulas: Contabilidad", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Contabilidad", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConceptos.setText(QtGui.QApplication.translate("MainWindow", "Conceptos", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConceptos.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+4", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBalance.setText(QtGui.QApplication.translate("MainWindow", "Balance General", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBalance.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+4", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEstado.setText(QtGui.QApplication.translate("MainWindow", "Estado de Resultados", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEstado.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+4", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMovements.setText(QtGui.QApplication.translate("MainWindow", "Movimientos Contables", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMovements.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+1", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAccounts.setText(QtGui.QApplication.translate("MainWindow", "Cuentas Contables", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAccounts.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+2", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConciliacion.setText(QtGui.QApplication.translate("MainWindow", "Conciliación Bancaria", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConciliacion.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+3", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNotasCD.setText(QtGui.QApplication.translate("MainWindow", "Movimientos Bancarios", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNotasCD.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+4", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("MainWindow", "Operaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLockSession.setText(QtGui.QApplication.translate("MainWindow", "Bloquear Sesión", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnlockSession.setText(QtGui.QApplication.translate("MainWindow", "Desbloquear Sesión", None, QtGui.QApplication.UnicodeUTF8))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

