# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/marcos/workspace/EsquipulasPy/src/ui/notacredito.ui'
#
# Created by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmNotaCredito(object):
    def setupUi(self, frmNotaCredito):
        frmNotaCredito.setObjectName("frmNotaCredito")
        frmNotaCredito.resize(529, 267)
        self.gridLayout = QtGui.QGridLayout(frmNotaCredito)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtGui.QLabel(frmNotaCredito)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.txtnotacredito = QtGui.QLineEdit(frmNotaCredito)
        self.txtnotacredito.setObjectName("txtnotacredito")
        self.gridLayout.addWidget(self.txtnotacredito, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(frmNotaCredito)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.txtBodega = QtGui.QLineEdit(frmNotaCredito)
        self.txtBodega.setReadOnly(True)
        self.txtBodega.setObjectName("txtBodega")
        self.gridLayout.addWidget(self.txtBodega, 0, 3, 1, 2)
        self.label_5 = QtGui.QLabel(frmNotaCredito)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.dtPicker = QtGui.QDateTimeEdit(frmNotaCredito)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtPicker.sizePolicy().hasHeightForWidth())
        self.dtPicker.setSizePolicy(sizePolicy)
        self.dtPicker.setReadOnly(True)
        self.dtPicker.setCalendarPopup(True)
        self.dtPicker.setObjectName("dtPicker")
        self.gridLayout.addWidget(self.dtPicker, 0, 6, 1, 1)
        self.label_3 = QtGui.QLabel(frmNotaCredito)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.txtCliente = QtGui.QLineEdit(frmNotaCredito)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCliente.sizePolicy().hasHeightForWidth())
        self.txtCliente.setSizePolicy(sizePolicy)
        self.txtCliente.setReadOnly(True)
        self.txtCliente.setObjectName("txtCliente")
        self.gridLayout.addWidget(self.txtCliente, 1, 1, 1, 6)
        self.label_6 = QtGui.QLabel(frmNotaCredito)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.txtConcepto = QtGui.QLineEdit(frmNotaCredito)
        self.txtConcepto.setReadOnly(True)
        self.txtConcepto.setObjectName("txtConcepto")
        self.gridLayout.addWidget(self.txtConcepto, 2, 1, 1, 6)
        self.groupBox_2 = QtGui.QGroupBox(frmNotaCredito)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.txtObservciones = QtGui.QPlainTextEdit(self.groupBox_2)
        self.txtObservciones.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtObservciones.sizePolicy().hasHeightForWidth())
        self.txtObservciones.setSizePolicy(sizePolicy)
        self.txtObservciones.setReadOnly(True)
        self.txtObservciones.setObjectName("txtObservciones")
        self.gridLayout_4.addWidget(self.txtObservciones, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 3, 0, 1, 4)
        self.groupBox = QtGui.QGroupBox(frmNotaCredito)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.lbliva = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbliva.sizePolicy().hasHeightForWidth())
        self.lbliva.setSizePolicy(sizePolicy)
        self.lbliva.setObjectName("lbliva")
        self.gridLayout_3.addWidget(self.lbliva, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 1)
        self.lblCosto = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCosto.sizePolicy().hasHeightForWidth())
        self.lblCosto.setSizePolicy(sizePolicy)
        self.lblCosto.setObjectName("lblCosto")
        self.gridLayout_3.addWidget(self.lblCosto, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 3, 0, 1, 1)
        self.lblDevolucion = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDevolucion.sizePolicy().hasHeightForWidth())
        self.lblDevolucion.setSizePolicy(sizePolicy)
        self.lblDevolucion.setObjectName("lblDevolucion")
        self.gridLayout_3.addWidget(self.lblDevolucion, 3, 1, 1, 1)
        self.lblsubtotal = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblsubtotal.sizePolicy().hasHeightForWidth())
        self.lblsubtotal.setSizePolicy(sizePolicy)
        self.lblsubtotal.setObjectName("lblsubtotal")
        self.gridLayout_3.addWidget(self.lblsubtotal, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 4, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(frmNotaCredito)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 1, 1, 6)
        self.label_7.setBuddy(self.txtBodega)
        self.label_5.setBuddy(self.dtPicker)
        self.label_3.setBuddy(frmNotaCredito.txtBill)
        self.label_6.setBuddy(frmNotaCredito.txtBill)

        self.retranslateUi(frmNotaCredito)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), frmNotaCredito.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), frmNotaCredito.reject)
        QtCore.QMetaObject.connectSlotsByName(frmNotaCredito)

    def retranslateUi(self, frmNotaCredito):
        frmNotaCredito.setWindowTitle(QtGui.QApplication.translate("frmNotaCredito", "Nota de Credito", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("frmNotaCredito", "<b>#Nota Credito</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("frmNotaCredito", "<b>Bodega</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("frmNotaCredito", "<b>Fecha</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmNotaCredito", "<b>Cliente</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("frmNotaCredito", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Concepto</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmNotaCredito", "Observaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmNotaCredito", "Totales", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("frmNotaCredito", "Subtotal: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("frmNotaCredito", "Impuesto: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lbliva.setText(QtGui.QApplication.translate("frmNotaCredito", "C$ 0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("frmNotaCredito", "Costo Total: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCosto.setText(QtGui.QApplication.translate("frmNotaCredito", "C$ 0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("frmNotaCredito", "Total Devolución: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDevolucion.setText(QtGui.QApplication.translate("frmNotaCredito", "C$ 0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.lblsubtotal.setText(QtGui.QApplication.translate("frmNotaCredito", "C$ 0.00", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    frmNotaCredito = QtGui.QDialog()
    ui = Ui_frmNotaCredito()
    ui.setupUi(frmNotaCredito)
    frmNotaCredito.show()
    sys.exit(app.exec_())

