# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\workspace\EsquipulasPy\src\ui\persona.ui'
#
# Created: Sun Aug 22 11:20:09 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_dlgPersona(object):
    def setupUi(self, dlgPersona):
        dlgPersona.setObjectName("dlgPersona")
        dlgPersona.resize(696, 391)
        dlgPersona.setWindowTitle("")
        self.verticalLayout_3 = QtGui.QVBoxLayout(dlgPersona)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtGui.QTabWidget(dlgPersona)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tabdetails = QtGui.QWidget()
        self.tabdetails.setObjectName("tabdetails")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabdetails)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbltitulo = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltitulo.sizePolicy().hasHeightForWidth())
        self.lbltitulo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbltitulo.setFont(font)
        self.lbltitulo.setText("")
        self.lbltitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltitulo.setObjectName("lbltitulo")
        self.verticalLayout.addWidget(self.lbltitulo)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblnombre = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblnombre.sizePolicy().hasHeightForWidth())
        self.lblnombre.setSizePolicy(sizePolicy)
        self.lblnombre.setObjectName("lblnombre")
        self.gridLayout.addWidget(self.lblnombre, 0, 0, 1, 1)
        self.swnombre = QtGui.QStackedWidget(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swnombre.sizePolicy().hasHeightForWidth())
        self.swnombre.setSizePolicy(sizePolicy)
        self.swnombre.setObjectName("swnombre")
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.page_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbnombre = QtGui.QComboBox(self.page_5)
        self.cbnombre.setEditable(True)
        self.cbnombre.setObjectName("cbnombre")
        self.horizontalLayout_5.addWidget(self.cbnombre)
        self.btnadd = QtGui.QPushButton(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnadd.sizePolicy().hasHeightForWidth())
        self.btnadd.setSizePolicy(sizePolicy)
        self.btnadd.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnadd.setIcon(icon)
        self.btnadd.setObjectName("btnadd")
        self.horizontalLayout_5.addWidget(self.btnadd)
        self.swnombre.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.page_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.txtnombre = QtGui.QLineEdit(self.page_6)
        self.txtnombre.setReadOnly(False)
        self.txtnombre.setObjectName("txtnombre")
        self.horizontalLayout_6.addWidget(self.txtnombre)
        self.btncancel = QtGui.QPushButton(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btncancel.sizePolicy().hasHeightForWidth())
        self.btncancel.setSizePolicy(sizePolicy)
        self.btncancel.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/dialog-cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btncancel.setIcon(icon1)
        self.btncancel.setObjectName("btncancel")
        self.horizontalLayout_6.addWidget(self.btncancel)
        self.swnombre.addWidget(self.page_6)
        self.gridLayout.addWidget(self.swnombre, 0, 2, 1, 8)
        self.label_12 = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 3)
        self.txtdireccion = QtGui.QLineEdit(self.tabdetails)
        self.txtdireccion.setMaxLength(200)
        self.txtdireccion.setReadOnly(False)
        self.txtdireccion.setObjectName("txtdireccion")
        self.gridLayout.addWidget(self.txtdireccion, 1, 3, 1, 7)
        self.label_11 = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 3)
        self.txtruc = QtGui.QLineEdit(self.tabdetails)
        self.txtruc.setMaxLength(45)
        self.txtruc.setDragEnabled(True)
        self.txtruc.setReadOnly(False)
        self.txtruc.setObjectName("txtruc")
        self.gridLayout.addWidget(self.txtruc, 2, 5, 1, 5)
        self.txtcorreo = QtGui.QLineEdit(self.tabdetails)
        self.txtcorreo.setMaxLength(45)
        self.txtcorreo.setReadOnly(False)
        self.txtcorreo.setObjectName("txtcorreo")
        self.gridLayout.addWidget(self.txtcorreo, 3, 3, 1, 7)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rbcontado = QtGui.QRadioButton(self.tabdetails)
        self.rbcontado.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbcontado.sizePolicy().hasHeightForWidth())
        self.rbcontado.setSizePolicy(sizePolicy)
        self.rbcontado.setChecked(True)
        self.rbcontado.setObjectName("rbcontado")
        self.horizontalLayout_7.addWidget(self.rbcontado)
        self.rbcredito = QtGui.QRadioButton(self.tabdetails)
        self.rbcredito.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbcredito.sizePolicy().hasHeightForWidth())
        self.rbcredito.setSizePolicy(sizePolicy)
        self.rbcredito.setObjectName("rbcredito")
        self.horizontalLayout_7.addWidget(self.rbcredito)
        self.gridLayout.addLayout(self.horizontalLayout_7, 4, 6, 1, 4)
        self.label_2 = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 3)
        self.txttelefono = QtGui.QLineEdit(self.tabdetails)
        self.txttelefono.setMaxLength(45)
        self.txttelefono.setReadOnly(False)
        self.txttelefono.setObjectName("txttelefono")
        self.gridLayout.addWidget(self.txttelefono, 2, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/document-edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabdetails, icon2, "")
        self.tabnavigation = QtGui.QWidget()
        self.tabnavigation.setObjectName("tabnavigation")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabnavigation)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tablenavigation = QtGui.QTableView(self.tabnavigation)
        self.tablenavigation.setAlternatingRowColors(True)
        self.tablenavigation.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablenavigation.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablenavigation.setObjectName("tablenavigation")
        self.tablenavigation.horizontalHeader().setStretchLastSection(True)
        self.tablenavigation.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tablenavigation)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_15 = QtGui.QLabel(self.tabnavigation)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.txtSearch = QtGui.QLineEdit(self.tabnavigation)
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout.addWidget(self.txtSearch)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabnavigation, icon3, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(dlgPersona)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.label_6.setBuddy(self.txtruc)
        self.label_15.setBuddy(self.txtSearch)

        self.retranslateUi(dlgPersona)
        self.tabWidget.setCurrentIndex(0)
        self.swnombre.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), dlgPersona.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), dlgPersona.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgPersona)

    def retranslateUi(self, dlgPersona):
        self.lblnombre.setText(QtGui.QApplication.translate("dlgPersona", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Nombre</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnadd.setToolTip(QtGui.QApplication.translate("dlgPersona", "Agregar una nueva persona", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("dlgPersona", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Dirección</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("dlgPersona", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Teléfono</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.rbcontado.setText(QtGui.QApplication.translate("dlgPersona", "Activo", None, QtGui.QApplication.UnicodeUTF8))
        self.rbcredito.setText(QtGui.QApplication.translate("dlgPersona", "Inactivo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dlgPersona", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">E-mail</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("dlgPersona", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">&amp;RUC/Cédula:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabdetails), None)
        self.label_15.setText(QtGui.QApplication.translate("dlgPersona", "&Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabnavigation), None)

import res_rc
