# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\workspace\EsquipulasPy\src\ui\recibo.ui'
#
# Created: Fri Jul 23 00:38:16 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmRecibo(object):
    def setupUi(self, frmRecibo):
        frmRecibo.setObjectName("frmRecibo")
        frmRecibo.resize(678, 630)
        self.centralwidget = QtGui.QWidget(frmRecibo)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tabdetails = QtGui.QWidget()
        self.tabdetails.setObjectName("tabdetails")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabdetails)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_4 = QtGui.QGroupBox(self.tabdetails)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lblnrec = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblnrec.sizePolicy().hasHeightForWidth())
        self.lblnrec.setSizePolicy(sizePolicy)
        self.lblnrec.setStyleSheet("border:1px solid #000")
        self.lblnrec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblnrec.setObjectName("lblnrec")
        self.gridLayout_2.addWidget(self.lblnrec, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.dtPicker = QtGui.QDateTimeEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtPicker.sizePolicy().hasHeightForWidth())
        self.dtPicker.setSizePolicy(sizePolicy)
        self.dtPicker.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dtPicker.setReadOnly(True)
        self.dtPicker.setCalendarPopup(True)
        self.dtPicker.setObjectName("dtPicker")
        self.gridLayout_2.addWidget(self.dtPicker, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.txtpersona = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtpersona.sizePolicy().hasHeightForWidth())
        self.txtpersona.setSizePolicy(sizePolicy)
        self.txtpersona.setMinimumSize(QtCore.QSize(0, 20))
        self.txtpersona.setReadOnly(True)
        self.txtpersona.setObjectName("txtpersona")
        self.gridLayout_2.addWidget(self.txtpersona, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.swconcepto = QtGui.QStackedWidget(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swconcepto.sizePolicy().hasHeightForWidth())
        self.swconcepto.setSizePolicy(sizePolicy)
        self.swconcepto.setMaximumSize(QtCore.QSize(16777215, 30))
        self.swconcepto.setObjectName("swconcepto")
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbconcepto = QtGui.QComboBox(self.page_5)
        self.cbconcepto.setMinimumSize(QtCore.QSize(0, 20))
        self.cbconcepto.setEditable(True)
        self.cbconcepto.setObjectName("cbconcepto")
        self.verticalLayout_4.addWidget(self.cbconcepto)
        self.swconcepto.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtconcepto = QtGui.QLineEdit(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtconcepto.sizePolicy().hasHeightForWidth())
        self.txtconcepto.setSizePolicy(sizePolicy)
        self.txtconcepto.setMinimumSize(QtCore.QSize(0, 20))
        self.txtconcepto.setStyleSheet("None")
        self.txtconcepto.setDragEnabled(True)
        self.txtconcepto.setReadOnly(True)
        self.txtconcepto.setObjectName("txtconcepto")
        self.horizontalLayout_2.addWidget(self.txtconcepto)
        self.swconcepto.addWidget(self.page_6)
        self.gridLayout_2.addWidget(self.swconcepto, 2, 1, 1, 3)
        self.ckretener = QtGui.QCheckBox(self.groupBox_4)
        self.ckretener.setEnabled(False)
        self.ckretener.setChecked(True)
        self.ckretener.setObjectName("ckretener")
        self.gridLayout_2.addWidget(self.ckretener, 3, 0, 1, 1)
        self.swtasaret = QtGui.QStackedWidget(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swtasaret.sizePolicy().hasHeightForWidth())
        self.swtasaret.setSizePolicy(sizePolicy)
        self.swtasaret.setMaximumSize(QtCore.QSize(80, 50))
        self.swtasaret.setObjectName("swtasaret")
        self.page_9 = QtGui.QWidget()
        self.page_9.setObjectName("page_9")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.page_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cbtasaret = QtGui.QComboBox(self.page_9)
        self.cbtasaret.setMinimumSize(QtCore.QSize(0, 20))
        self.cbtasaret.setEditable(False)
        self.cbtasaret.setObjectName("cbtasaret")
        self.horizontalLayout_9.addWidget(self.cbtasaret)
        self.label_8 = QtGui.QLabel(self.page_9)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.swtasaret.addWidget(self.page_9)
        self.page_10 = QtGui.QWidget()
        self.page_10.setObjectName("page_10")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.page_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.txttasaret = QtGui.QLineEdit(self.page_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txttasaret.sizePolicy().hasHeightForWidth())
        self.txttasaret.setSizePolicy(sizePolicy)
        self.txttasaret.setMinimumSize(QtCore.QSize(0, 20))
        self.txttasaret.setStyleSheet("None")
        self.txttasaret.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txttasaret.setDragEnabled(True)
        self.txttasaret.setReadOnly(True)
        self.txttasaret.setObjectName("txttasaret")
        self.horizontalLayout_10.addWidget(self.txttasaret)
        self.label_9 = QtGui.QLabel(self.page_10)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.swtasaret.addWidget(self.page_10)
        self.gridLayout_2.addWidget(self.swtasaret, 3, 1, 2, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 2, 1, 1)
        self.lblnreten = QtGui.QLabel(self.groupBox_4)
        self.lblnreten.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblnreten.sizePolicy().hasHeightForWidth())
        self.lblnreten.setSizePolicy(sizePolicy)
        self.lblnreten.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lblnreten.setStyleSheet("border:1px solid #000")
        self.lblnreten.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblnreten.setObjectName("lblnreten")
        self.gridLayout_2.addWidget(self.lblnreten, 3, 3, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 4, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 4, 2, 1, 1)
        self.lbltotalreten = QtGui.QLabel(self.groupBox_4)
        self.lbltotalreten.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltotalreten.sizePolicy().hasHeightForWidth())
        self.lbltotalreten.setSizePolicy(sizePolicy)
        self.lbltotalreten.setMinimumSize(QtCore.QSize(0, 20))
        self.lbltotalreten.setStyleSheet("border:1px solid #000")
        self.lbltotalreten.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbltotalreten.setObjectName("lbltotalreten")
        self.gridLayout_2.addWidget(self.lbltotalreten, 4, 3, 1, 1)
        self.mtxtobservaciones = QtGui.QPlainTextEdit(self.groupBox_4)
        self.mtxtobservaciones.setEnabled(True)
        self.mtxtobservaciones.setMaximumSize(QtCore.QSize(16777215, 50))
        self.mtxtobservaciones.setReadOnly(True)
        self.mtxtobservaciones.setObjectName("mtxtobservaciones")
        self.gridLayout_2.addWidget(self.mtxtobservaciones, 5, 0, 1, 4)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.splitter = QtGui.QSplitter(self.tabdetails)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.swcliente = QtGui.QStackedWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swcliente.sizePolicy().hasHeightForWidth())
        self.swcliente.setSizePolicy(sizePolicy)
        self.swcliente.setStyleSheet("padding:0px;")
        self.swcliente.setObjectName("swcliente")
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName("page_7")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.page_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbcliente = QtGui.QComboBox(self.page_7)
        self.cbcliente.setMinimumSize(QtCore.QSize(0, 20))
        self.cbcliente.setEditable(True)
        self.cbcliente.setObjectName("cbcliente")
        self.horizontalLayout_6.addWidget(self.cbcliente)
        self.swcliente.addWidget(self.page_7)
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName("page_8")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.page_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtcliente = QtGui.QLineEdit(self.page_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtcliente.sizePolicy().hasHeightForWidth())
        self.txtcliente.setSizePolicy(sizePolicy)
        self.txtcliente.setMinimumSize(QtCore.QSize(0, 20))
        self.txtcliente.setStyleSheet("padding:0px;")
        self.txtcliente.setDragEnabled(True)
        self.txtcliente.setReadOnly(True)
        self.txtcliente.setObjectName("txtcliente")
        self.horizontalLayout_3.addWidget(self.txtcliente)
        self.swcliente.addWidget(self.page_8)
        self.horizontalLayout_4.addWidget(self.swcliente)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frbotones = QtGui.QFrame(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frbotones.sizePolicy().hasHeightForWidth())
        self.frbotones.setSizePolicy(sizePolicy)
        self.frbotones.setMinimumSize(QtCore.QSize(300, 0))
        self.frbotones.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frbotones.setStyleSheet("padding:0px;")
        self.frbotones.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frbotones.setFrameShadow(QtGui.QFrame.Raised)
        self.frbotones.setObjectName("frbotones")
        self.gridLayout = QtGui.QGridLayout(self.frbotones)
        self.gridLayout.setObjectName("gridLayout")
        self.btnaddall = QtGui.QPushButton(self.frbotones)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnaddall.sizePolicy().hasHeightForWidth())
        self.btnaddall.setSizePolicy(sizePolicy)
        self.btnaddall.setMinimumSize(QtCore.QSize(26, 16))
        self.btnaddall.setStyleSheet("background: url(:/icons/res/arrow-right-double.png) no-repeat;")
        self.btnaddall.setText("")
        self.btnaddall.setFlat(True)
        self.btnaddall.setObjectName("btnaddall")
        self.gridLayout.addWidget(self.btnaddall, 1, 1, 1, 1)
        self.tablefacturas = QtGui.QTableView(self.frbotones)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablefacturas.sizePolicy().hasHeightForWidth())
        self.tablefacturas.setSizePolicy(sizePolicy)
        self.tablefacturas.setMinimumSize(QtCore.QSize(0, 5))
        self.tablefacturas.setStyleSheet("padding:0px;")
        self.tablefacturas.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablefacturas.setObjectName("tablefacturas")
        self.gridLayout.addWidget(self.tablefacturas, 0, 0, 4, 1)
        self.btnadd = QtGui.QPushButton(self.frbotones)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnadd.sizePolicy().hasHeightForWidth())
        self.btnadd.setSizePolicy(sizePolicy)
        self.btnadd.setStyleSheet("background: url(:/icons/res/arrow-right.png) no-repeat;\n"
"")
        self.btnadd.setText("")
        self.btnadd.setFlat(True)
        self.btnadd.setObjectName("btnadd")
        self.gridLayout.addWidget(self.btnadd, 0, 1, 1, 1)
        self.btnremove = QtGui.QPushButton(self.frbotones)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnremove.sizePolicy().hasHeightForWidth())
        self.btnremove.setSizePolicy(sizePolicy)
        self.btnremove.setStyleSheet("background: url(:/icons/res/arrow-right.png) no-repeat;\n"
"")
        self.btnremove.setText("")
        self.btnremove.setFlat(True)
        self.btnremove.setObjectName("btnremove")
        self.gridLayout.addWidget(self.btnremove, 2, 1, 1, 1)
        self.btnremoveall = QtGui.QPushButton(self.frbotones)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnremoveall.sizePolicy().hasHeightForWidth())
        self.btnremoveall.setSizePolicy(sizePolicy)
        self.btnremoveall.setMinimumSize(QtCore.QSize(26, 18))
        self.btnremoveall.setStyleSheet("background: url(:/icons/res/arrow-left-double.png) no-repeat;\n"
"")
        self.btnremoveall.setText("")
        self.btnremoveall.setFlat(True)
        self.btnremoveall.setObjectName("btnremoveall")
        self.gridLayout.addWidget(self.btnremoveall, 3, 1, 1, 1)
        self.horizontalLayout_8.addWidget(self.frbotones)
        self.frame_2 = QtGui.QFrame(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("padding:0px;")
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableabonos = QtGui.QTableView(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableabonos.sizePolicy().hasHeightForWidth())
        self.tableabonos.setSizePolicy(sizePolicy)
        self.tableabonos.setMinimumSize(QtCore.QSize(0, 5))
        self.tableabonos.setStyleSheet("padding:0px;")
        self.tableabonos.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableabonos.setObjectName("tableabonos")
        self.verticalLayout_3.addWidget(self.tableabonos)
        self.horizontalLayout_8.addWidget(self.frame_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.lbltotal = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltotal.sizePolicy().hasHeightForWidth())
        self.lbltotal.setSizePolicy(sizePolicy)
        self.lbltotal.setMinimumSize(QtCore.QSize(0, 20))
        self.lbltotal.setStyleSheet("border:1px solid #000")
        self.lbltotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbltotal.setObjectName("lbltotal")
        self.horizontalLayout_5.addWidget(self.lbltotal)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.groupBox_3 = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tabledetails = QtGui.QTableView(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabledetails.sizePolicy().hasHeightForWidth())
        self.tabledetails.setSizePolicy(sizePolicy)
        self.tabledetails.setMinimumSize(QtCore.QSize(0, 70))
        self.tabledetails.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabledetails.setObjectName("tabledetails")
        self.horizontalLayout_7.addWidget(self.tabledetails)
        self.verticalLayout_6.addWidget(self.splitter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/document-edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabdetails, icon, "")
        self.tabnavigation = QtGui.QWidget()
        self.tabnavigation.setObjectName("tabnavigation")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabnavigation)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tablenavigation = QtGui.QTableView(self.tabnavigation)
        self.tablenavigation.setAlternatingRowColors(True)
        self.tablenavigation.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablenavigation.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablenavigation.setObjectName("tablenavigation")
        self.tablenavigation.horizontalHeader().setStretchLastSection(True)
        self.tablenavigation.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tablenavigation)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtGui.QLabel(self.tabnavigation)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.txtSearch = QtGui.QLineEdit(self.tabnavigation)
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout.addWidget(self.txtSearch)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabnavigation, icon1, "")
        self.verticalLayout.addWidget(self.tabWidget)
        frmRecibo.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(frmRecibo)
        self.statusbar.setObjectName("statusbar")
        frmRecibo.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(frmRecibo)
        self.toolBar.setObjectName("toolBar")
        frmRecibo.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionNew = QtGui.QAction(frmRecibo)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon2)
        self.actionNew.setObjectName("actionNew")
        self.actionPreview = QtGui.QAction(frmRecibo)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/document-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreview.setIcon(icon3)
        self.actionPreview.setObjectName("actionPreview")
        self.actionGoFirst = QtGui.QAction(frmRecibo)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res/go-first.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGoFirst.setIcon(icon4)
        self.actionGoFirst.setObjectName("actionGoFirst")
        self.actionGoPrevious = QtGui.QAction(frmRecibo)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/res/go-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGoPrevious.setIcon(icon5)
        self.actionGoPrevious.setObjectName("actionGoPrevious")
        self.actionGoNext = QtGui.QAction(frmRecibo)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/res/go-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGoNext.setIcon(icon6)
        self.actionGoNext.setObjectName("actionGoNext")
        self.actionGoLast = QtGui.QAction(frmRecibo)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/res/go-last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGoLast.setIcon(icon7)
        self.actionGoLast.setObjectName("actionGoLast")
        self.actionSave = QtGui.QAction(frmRecibo)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/res/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon8)
        self.actionSave.setObjectName("actionSave")
        self.actionCancel = QtGui.QAction(frmRecibo)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/res/dialog-cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCancel.setIcon(icon9)
        self.actionCancel.setObjectName("actionCancel")
        self.actionEditCell = QtGui.QAction(frmRecibo)
        self.actionEditCell.setIcon(icon)
        self.actionEditCell.setObjectName("actionEditCell")
        self.actionDeleteRow = QtGui.QAction(frmRecibo)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/res/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteRow.setIcon(icon10)
        self.actionDeleteRow.setObjectName("actionDeleteRow")
        self.actionCopy = QtGui.QAction(frmRecibo)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/res/edit-copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon11)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtGui.QAction(frmRecibo)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/res/edit-cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon12)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtGui.QAction(frmRecibo)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/res/edit-paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon13)
        self.actionPaste.setObjectName("actionPaste")
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionCancel)
        self.toolBar.addAction(self.actionPreview)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGoFirst)
        self.toolBar.addAction(self.actionGoPrevious)
        self.toolBar.addAction(self.actionGoNext)
        self.toolBar.addAction(self.actionGoLast)
        self.label_5.setBuddy(self.dtPicker)
        self.label_6.setBuddy(self.txtconcepto)
        self.label_4.setBuddy(self.txtSearch)

        self.retranslateUi(frmRecibo)
        self.tabWidget.setCurrentIndex(0)
        self.swconcepto.setCurrentIndex(1)
        self.swtasaret.setCurrentIndex(0)
        self.swcliente.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(frmRecibo)
        frmRecibo.setTabOrder(self.txtpersona, self.cbconcepto)
        frmRecibo.setTabOrder(self.cbconcepto, self.ckretener)
        frmRecibo.setTabOrder(self.ckretener, self.mtxtobservaciones)
        frmRecibo.setTabOrder(self.mtxtobservaciones, self.cbcliente)
        frmRecibo.setTabOrder(self.cbcliente, self.tablefacturas)
        frmRecibo.setTabOrder(self.tablefacturas, self.btnadd)
        frmRecibo.setTabOrder(self.btnadd, self.tableabonos)
        frmRecibo.setTabOrder(self.tableabonos, self.btnaddall)
        frmRecibo.setTabOrder(self.btnaddall, self.tablenavigation)
        frmRecibo.setTabOrder(self.tablenavigation, self.txtSearch)
        frmRecibo.setTabOrder(self.txtSearch, self.btnremove)
        frmRecibo.setTabOrder(self.btnremove, self.btnremoveall)
        frmRecibo.setTabOrder(self.btnremoveall, self.txtcliente)
        frmRecibo.setTabOrder(self.txtcliente, self.txtconcepto)

    def retranslateUi(self, frmRecibo):
        frmRecibo.setWindowTitle(QtGui.QApplication.translate("frmRecibo", "Recibo Oficial de Caja", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("frmRecibo", "Datos del Recibo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmRecibo", "Recibo No.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblnrec.setText(QtGui.QApplication.translate("frmRecibo", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("frmRecibo", "&Fecha", None, QtGui.QApplication.UnicodeUTF8))
        self.dtPicker.setDisplayFormat(QtGui.QApplication.translate("frmRecibo", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmRecibo", "Recibimos de:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("frmRecibo", "En concepto de:", None, QtGui.QApplication.UnicodeUTF8))
        self.ckretener.setText(QtGui.QApplication.translate("frmRecibo", "Con Retención", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("frmRecibo", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.txttasaret.setText(QtGui.QApplication.translate("frmRecibo", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("frmRecibo", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("frmRecibo", "Retención No.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblnreten.setText(QtGui.QApplication.translate("frmRecibo", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("frmRecibo", "Observaciones ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("frmRecibo", "Total Retenido", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltotalreten.setText(QtGui.QApplication.translate("frmRecibo", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmRecibo", "Detalle de Abono a Facturas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmRecibo", "Cliente:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("frmRecibo", "La cantidad de:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltotal.setText(QtGui.QApplication.translate("frmRecibo", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("frmRecibo", "Especifique los tipos de pagos", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabdetails), None)
        self.label_4.setText(QtGui.QApplication.translate("frmRecibo", "&Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabnavigation), None)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("frmRecibo", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("frmRecibo", "Nuevo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("frmRecibo", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreview.setText(QtGui.QApplication.translate("frmRecibo", "Previsualizar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoFirst.setText(QtGui.QApplication.translate("frmRecibo", "Ir al Primer Registro", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoPrevious.setText(QtGui.QApplication.translate("frmRecibo", "Ir al Registro Anterior", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoNext.setText(QtGui.QApplication.translate("frmRecibo", "Ir al siguiente registro", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoLast.setText(QtGui.QApplication.translate("frmRecibo", "Ir al ultimo registro", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("frmRecibo", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCancel.setText(QtGui.QApplication.translate("frmRecibo", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditCell.setText(QtGui.QApplication.translate("frmRecibo", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditCell.setShortcut(QtGui.QApplication.translate("frmRecibo", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeleteRow.setText(QtGui.QApplication.translate("frmRecibo", "Borrar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("frmRecibo", "Copiar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("frmRecibo", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("frmRecibo", "Cortar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setShortcut(QtGui.QApplication.translate("frmRecibo", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("frmRecibo", "Pegar", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
