# -*- coding: utf-8 -*-
'''
Created on 06/07/2010

@author: Luis Carlos Mejia
'''
#contantes de modulos
IDCONTABILIDAD = 3
IDINVENTARIO = 4

#conceptos
IDCONCEPTODEPOSITO = 0


# constantes de tipos de documento
IDFACTURA = 5
IDLIQUIDACION = 7
IDDEVOLUCION = 10
IDND = 11
IDCHEQUE = 12
IDDEPOSITO = 13
IDNC = 14
IDRECIBO = 18
IDRETENCION = 19
IDENTRADALOCAL = 21
IDARQUEO = 23
IDAJUSTECONTABLE = 24
IDCONCILIACION = 25
IDERROR = 26
IDKARDEX = 27

#TIPOS DE PERSONA
CLIENTE = 1
PROVEEDOR = 2
VENDEDOR = 3
USUARIO = 4

#TIPOS COSTO
IVA = 1
ISC = 2
DAI = 3
SPE = 4
TSIM = 5
ISO = 6
COMISION = 7
RETENCION10 = 8
IMPUESTOALVALOR = 9
RETENCION2 = 10
