# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/apertura.ui'
#
# Created: Mon Oct 18 00:30:07 2010
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dlgApertura(object):
    def setupUi(self, dlgApertura):
        dlgApertura.setObjectName(_fromUtf8("dlgApertura"))
        dlgApertura.setWindowModality(QtCore.Qt.ApplicationModal)
        dlgApertura.resize(346, 276)
        dlgApertura.setMaximumSize(QtCore.QSize(16777215, 276))
        self.verticalLayout = QtGui.QVBoxLayout(dlgApertura)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(dlgApertura)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.txtUsuario = QtGui.QLineEdit(dlgApertura)
        self.txtUsuario.setReadOnly(False)
        self.txtUsuario.setObjectName(_fromUtf8("txtUsuario"))
        self.gridLayout.addWidget(self.txtUsuario, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(dlgApertura)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.dtFechaTime = QtGui.QDateTimeEdit(dlgApertura)
        self.dtFechaTime.setCalendarPopup(True)
        self.dtFechaTime.setObjectName(_fromUtf8("dtFechaTime"))
        self.gridLayout.addWidget(self.dtFechaTime, 1, 1, 1, 1)
        self.label = QtGui.QLabel(dlgApertura)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.swcaja = QtGui.QStackedWidget(dlgApertura)
        self.swcaja.setMaximumSize(QtCore.QSize(16777215, 200))
        self.swcaja.setObjectName(_fromUtf8("swcaja"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cbcaja = QtGui.QComboBox(self.page)
        self.cbcaja.setObjectName(_fromUtf8("cbcaja"))
        self.horizontalLayout.addWidget(self.cbcaja)
        self.swcaja.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.txtcaja = QtGui.QLineEdit(self.page_2)
        self.txtcaja.setReadOnly(False)
        self.txtcaja.setObjectName(_fromUtf8("txtcaja"))
        self.horizontalLayout_2.addWidget(self.txtcaja)
        self.swcaja.addWidget(self.page_2)
        self.gridLayout.addWidget(self.swcaja, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(dlgApertura)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.txtSaldoC = QtGui.QDoubleSpinBox(dlgApertura)
        self.txtSaldoC.setDecimals(4)
        self.txtSaldoC.setMaximum(1000000000.0)
        self.txtSaldoC.setObjectName(_fromUtf8("txtSaldoC"))
        self.gridLayout.addWidget(self.txtSaldoC, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(dlgApertura)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.txtSaldoD = QtGui.QDoubleSpinBox(dlgApertura)
        self.txtSaldoD.setDecimals(4)
        self.txtSaldoD.setMaximum(1000000000.0)
        self.txtSaldoD.setObjectName(_fromUtf8("txtSaldoD"))
        self.gridLayout.addWidget(self.txtSaldoD, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.groupBox = QtGui.QGroupBox(dlgApertura)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.txtUser = QtGui.QLineEdit(self.groupBox)
        self.txtUser.setReadOnly(False)
        self.txtUser.setObjectName(_fromUtf8("txtUser"))
        self.gridLayout_2.addWidget(self.txtUser, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.txtPassword = QtGui.QLineEdit(self.groupBox)
        self.txtPassword.setReadOnly(False)
        self.txtPassword.setObjectName(_fromUtf8("txtPassword"))
        self.gridLayout_2.addWidget(self.txtPassword, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(dlgApertura)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(dlgApertura)
        self.swcaja.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), dlgApertura.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), dlgApertura.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgApertura)
        dlgApertura.setTabOrder(self.cbcaja, self.txtSaldoC)
        dlgApertura.setTabOrder(self.txtSaldoC, self.txtSaldoD)
        dlgApertura.setTabOrder(self.txtSaldoD, self.txtUser)
        dlgApertura.setTabOrder(self.txtUser, self.txtPassword)
        dlgApertura.setTabOrder(self.txtPassword, self.buttonBox)
        dlgApertura.setTabOrder(self.buttonBox, self.dtFechaTime)
        dlgApertura.setTabOrder(self.dtFechaTime, self.txtUsuario)
        dlgApertura.setTabOrder(self.txtUsuario, self.txtcaja)

    def retranslateUi(self, dlgApertura):
        dlgApertura.setWindowTitle(QtGui.QApplication.translate("dlgApertura", "Apertura de Caja", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("dlgApertura", "Cajero:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("dlgApertura", "Fecha", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dlgApertura", "Caja", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("dlgApertura", "Monto C$", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dlgApertura", "Monto US$", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("dlgApertura", "Autorizacion Por:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("dlgApertura", "Usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("dlgApertura", "Contraseña", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    dlgApertura = QtGui.QDialog()
    ui = Ui_dlgApertura()
    ui.setupUi(dlgApertura)
    dlgApertura.show()
    sys.exit(app.exec_())

