# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/balancegeneral.ui'
#
# Created: Mon Aug  9 22:37:25 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmBalanceGeneral(object):
    def setupUi(self, FrmBalanceGeneral):
        FrmBalanceGeneral.setObjectName("frmBalanceGeneral")
        FrmBalanceGeneral.resize(800, 634)
        self.centralwidget = QtGui.QWidget(FrmBalanceGeneral)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dtPicker = QtGui.QDateTimeEdit(self.centralwidget)
        self.dtPicker.setAlignment(QtCore.Qt.AlignCenter)
        self.dtPicker.setObjectName("dtPicker")
        self.verticalLayout_5.addWidget(self.dtPicker)
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_2 = QtGui.QGroupBox(self.splitter_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 240))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.activoTree = QtGui.QTreeView(self.groupBox_2)
        self.activoTree.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.activoTree.setAlternatingRowColors(True)
        self.activoTree.setObjectName("activoTree")
        self.verticalLayout_4.addWidget(self.activoTree)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox_3 = QtGui.QGroupBox(self.splitter)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 240))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pasivoTree = QtGui.QTreeView(self.groupBox_3)
        self.pasivoTree.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.pasivoTree.setAlternatingRowColors(True)
        self.pasivoTree.setObjectName("pasivoTree")
        self.verticalLayout.addWidget(self.pasivoTree)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbltotallibro_4 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltotallibro_4.sizePolicy().hasHeightForWidth())
        self.lbltotallibro_4.setSizePolicy(sizePolicy)
        self.lbltotallibro_4.setMinimumSize(QtCore.QSize(0, 8))
        self.lbltotallibro_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbltotallibro_4.setObjectName("lbltotallibro_4")
        self.horizontalLayout_6.addWidget(self.lbltotallibro_4)
        self.txtpasivo = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtpasivo.sizePolicy().hasHeightForWidth())
        self.txtpasivo.setSizePolicy(sizePolicy)
        self.txtpasivo.setMinimumSize(QtCore.QSize(0, 0))
        self.txtpasivo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtpasivo.setReadOnly(True)
        self.txtpasivo.setObjectName("txtpasivo")
        self.horizontalLayout_6.addWidget(self.txtpasivo)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.layoutWidget_3 = QtGui.QWidget(self.splitter)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.layoutWidget_3)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.capitalTree = QtGui.QTreeView(self.groupBox)
        self.capitalTree.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.capitalTree.setAlternatingRowColors(True)
        self.capitalTree.setObjectName("capitalTree")
        self.verticalLayout_2.addWidget(self.capitalTree)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lbltotallibro_5 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltotallibro_5.sizePolicy().hasHeightForWidth())
        self.lbltotallibro_5.setSizePolicy(sizePolicy)
        self.lbltotallibro_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbltotallibro_5.setObjectName("lbltotallibro_5")
        self.horizontalLayout_8.addWidget(self.lbltotallibro_5)
        self.txtcapital = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtcapital.sizePolicy().hasHeightForWidth())
        self.txtcapital.setSizePolicy(sizePolicy)
        self.txtcapital.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtcapital.setReadOnly(True)
        self.txtcapital.setObjectName("txtcapital")
        self.horizontalLayout_8.addWidget(self.txtcapital)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_5.addWidget(self.splitter_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbltotallibro = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltotallibro.sizePolicy().hasHeightForWidth())
        self.lbltotallibro.setSizePolicy(sizePolicy)
        self.lbltotallibro.setMinimumSize(QtCore.QSize(0, 8))
        self.lbltotallibro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbltotallibro.setObjectName("lbltotallibro")
        self.horizontalLayout_2.addWidget(self.lbltotallibro)
        self.txtactivo = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtactivo.sizePolicy().hasHeightForWidth())
        self.txtactivo.setSizePolicy(sizePolicy)
        self.txtactivo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtactivo.setReadOnly(True)
        self.txtactivo.setObjectName("txtactivo")
        self.horizontalLayout_2.addWidget(self.txtactivo)
        self.lbltotalbanco = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltotalbanco.sizePolicy().hasHeightForWidth())
        self.lbltotalbanco.setSizePolicy(sizePolicy)
        self.lbltotalbanco.setMinimumSize(QtCore.QSize(0, 8))
        self.lbltotalbanco.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbltotalbanco.setObjectName("lbltotalbanco")
        self.horizontalLayout_2.addWidget(self.lbltotalbanco)
        self.txtpasivocapital = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtpasivocapital.sizePolicy().hasHeightForWidth())
        self.txtpasivocapital.setSizePolicy(sizePolicy)
        self.txtpasivocapital.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtpasivocapital.setReadOnly(True)
        self.txtpasivocapital.setObjectName("txtpasivocapital")
        self.horizontalLayout_2.addWidget(self.txtpasivocapital)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        FrmBalanceGeneral.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(FrmBalanceGeneral)
        self.toolBar.setObjectName("toolBar")
        FrmBalanceGeneral.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionPreview = QtGui.QAction(FrmBalanceGeneral)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/document-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreview.setIcon(icon)
        self.actionPreview.setObjectName("actionPreview")
        self.toolBar.addAction(self.actionPreview)

        self.retranslateUi(FrmBalanceGeneral)
        QtCore.QMetaObject.connectSlotsByName(FrmBalanceGeneral)

    def retranslateUi(self, FrmBalanceGeneral):
        FrmBalanceGeneral.setWindowTitle(QtGui.QApplication.translate("frmBalanceGeneral", "Balance General", None, QtGui.QApplication.UnicodeUTF8))
        self.dtPicker.setDisplayFormat(QtGui.QApplication.translate("frmBalanceGeneral", "MMMM yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmBalanceGeneral", "Activos", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("frmBalanceGeneral", "Pasivos", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltotallibro_4.setText(QtGui.QApplication.translate("frmBalanceGeneral", "Total Pasivo", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmBalanceGeneral", "Capital", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltotallibro_5.setText(QtGui.QApplication.translate("frmBalanceGeneral", "Total Capital", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltotallibro.setText(QtGui.QApplication.translate("frmBalanceGeneral", "Total Activo:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltotalbanco.setText(QtGui.QApplication.translate("frmBalanceGeneral", "Total Pasivo más Capital", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("frmBalanceGeneral", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreview.setText(QtGui.QApplication.translate("frmBalanceGeneral", "Previsualizar", None, QtGui.QApplication.UnicodeUTF8))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FrmBalanceGeneral = QtGui.QMainWindow()
    ui = Ui_frmBalanceGeneral()
    ui.setupUi(FrmBalanceGeneral)
    FrmBalanceGeneral.show()
    sys.exit(app.exec_())

