# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindowcaja.ui'
#
# Created: Mon Oct 18 00:31:48 2010
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1151, 708)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        brush = QtGui.QBrush(QtGui.QColor(125, 124, 123))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setViewMode(QtGui.QMdiArea.TabbedView)
        self.mdiArea.setTabShape(QtGui.QTabWidget.Rounded)
        self.mdiArea.setTabPosition(QtGui.QTabWidget.North)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.horizontalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(230, 181))
        self.dockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolBox = QtGui.QToolBox(self.dockWidgetContents_2)
        self.toolBox.setEnabled(True)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_2 = QtGui.QWidget()
        self.page_2.setEnabled(True)
        self.page_2.setGeometry(QtCore.QRect(0, 0, 214, 588))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnApertura = QtGui.QPushButton(self.page_2)
        self.btnApertura.setEnabled(True)
        self.btnApertura.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.btnApertura.setFont(font)
        self.btnApertura.setAutoFillBackground(False)
        self.btnApertura.setIconSize(QtCore.QSize(64, 64))
        self.btnApertura.setFlat(False)
        self.btnApertura.setObjectName(_fromUtf8("btnApertura"))
        self.gridLayout_2.addWidget(self.btnApertura, 0, 0, 1, 1)
        self.btnfactura = QtGui.QPushButton(self.page_2)
        self.btnfactura.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnfactura.sizePolicy().hasHeightForWidth())
        self.btnfactura.setSizePolicy(sizePolicy)
        self.btnfactura.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnfactura.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/res/view-financial-categories.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnfactura.setIcon(icon1)
        self.btnfactura.setIconSize(QtCore.QSize(64, 64))
        self.btnfactura.setFlat(False)
        self.btnfactura.setObjectName(_fromUtf8("btnfactura"))
        self.gridLayout_2.addWidget(self.btnfactura, 1, 0, 1, 1)
        self.btnrecibo = QtGui.QPushButton(self.page_2)
        self.btnrecibo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnrecibo.sizePolicy().hasHeightForWidth())
        self.btnrecibo.setSizePolicy(sizePolicy)
        self.btnrecibo.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnrecibo.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/res/view-documents-finances.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnrecibo.setIcon(icon2)
        self.btnrecibo.setIconSize(QtCore.QSize(64, 64))
        self.btnrecibo.setFlat(False)
        self.btnrecibo.setObjectName(_fromUtf8("btnrecibo"))
        self.gridLayout_2.addWidget(self.btnrecibo, 2, 0, 1, 1)
        self.btnpago = QtGui.QPushButton(self.page_2)
        self.btnpago.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnpago.sizePolicy().hasHeightForWidth())
        self.btnpago.setSizePolicy(sizePolicy)
        self.btnpago.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnpago.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/pays.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnpago.setIcon(icon3)
        self.btnpago.setIconSize(QtCore.QSize(64, 64))
        self.btnpago.setFlat(False)
        self.btnpago.setObjectName(_fromUtf8("btnpago"))
        self.gridLayout_2.addWidget(self.btnpago, 3, 0, 1, 1)
        self.btnDevolutions = QtGui.QPushButton(self.page_2)
        self.btnDevolutions.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDevolutions.sizePolicy().hasHeightForWidth())
        self.btnDevolutions.setSizePolicy(sizePolicy)
        self.btnDevolutions.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnDevolutions.setFont(font)
        self.btnDevolutions.setIconSize(QtCore.QSize(32, 32))
        self.btnDevolutions.setFlat(False)
        self.btnDevolutions.setObjectName(_fromUtf8("btnDevolutions"))
        self.gridLayout_2.addWidget(self.btnDevolutions, 4, 0, 1, 1)
        self.btnArqueo = QtGui.QPushButton(self.page_2)
        self.btnArqueo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnArqueo.sizePolicy().hasHeightForWidth())
        self.btnArqueo.setSizePolicy(sizePolicy)
        self.btnArqueo.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnArqueo.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/res/reconcile-finish.svgz")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnArqueo.setIcon(icon4)
        self.btnArqueo.setIconSize(QtCore.QSize(64, 64))
        self.btnArqueo.setFlat(False)
        self.btnArqueo.setObjectName(_fromUtf8("btnArqueo"))
        self.gridLayout_2.addWidget(self.btnArqueo, 5, 0, 1, 1)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox)
        self.dockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionLockSession = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/object-locked.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLockSession.setIcon(icon5)
        self.actionLockSession.setObjectName(_fromUtf8("actionLockSession"))
        self.actionUnlockSession = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/object-unlocked.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnlockSession.setIcon(icon6)
        self.actionUnlockSession.setVisible(False)
        self.actionUnlockSession.setObjectName(_fromUtf8("actionUnlockSession"))
        self.actionClients = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/res/preferences-desktop-personal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClients.setIcon(icon7)
        self.actionClients.setObjectName(_fromUtf8("actionClients"))
        self.toolBar.addAction(self.actionLockSession)
        self.toolBar.addAction(self.actionUnlockSession)
        self.toolBar.addAction(self.actionClients)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Llantera Esquipulas Caja", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Caja", None, QtGui.QApplication.UnicodeUTF8))
        self.btnApertura.setText(QtGui.QApplication.translate("MainWindow", "Apertura de Caja", None, QtGui.QApplication.UnicodeUTF8))
        self.btnfactura.setText(QtGui.QApplication.translate("MainWindow", "Facturas", None, QtGui.QApplication.UnicodeUTF8))
        self.btnrecibo.setText(QtGui.QApplication.translate("MainWindow", "Recibos", None, QtGui.QApplication.UnicodeUTF8))
        self.btnpago.setText(QtGui.QApplication.translate("MainWindow", "Pagos en\n"
"Efectivo", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDevolutions.setText(QtGui.QApplication.translate("MainWindow", "Devoluciones", None, QtGui.QApplication.UnicodeUTF8))
        self.btnArqueo.setText(QtGui.QApplication.translate("MainWindow", "Arqueo", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("MainWindow", "Movimientos", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLockSession.setText(QtGui.QApplication.translate("MainWindow", "Bloquear Sesión", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnlockSession.setText(QtGui.QApplication.translate("MainWindow", "Desbloquear Sesión", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClients.setText(QtGui.QApplication.translate("MainWindow", "clients", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClients.setToolTip(QtGui.QApplication.translate("MainWindow", "Crear un Nuevo Cliente", None, QtGui.QApplication.UnicodeUTF8))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

