# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\workspace\EsquipulasPy\esquipulaspy\ui\operations.ui'
#
# Created: Sun May 01 21:55:24 2011
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmOperations(object):
    def setupUi(self, frmOperations):
        frmOperations.setObjectName(_fromUtf8("frmOperations"))
        frmOperations.resize(800, 600)
        self.centralwidget = QtGui.QWidget(frmOperations)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.txtSearch = QtGui.QLineEdit(self.widget)
        self.txtSearch.setObjectName(_fromUtf8("txtSearch"))
        self.gridLayout.addWidget(self.txtSearch, 0, 1, 1, 1)
        self.tableNavigation = QtGui.QTableView(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableNavigation.sizePolicy().hasHeightForWidth())
        self.tableNavigation.setSizePolicy(sizePolicy)
        self.tableNavigation.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableNavigation.setAlternatingRowColors(True)
        self.tableNavigation.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableNavigation.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableNavigation.setObjectName(_fromUtf8("tableNavigation"))
        self.gridLayout.addWidget(self.tableNavigation, 1, 0, 1, 2)
        self.widget1 = QtGui.QWidget(self.splitter)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.dtPicker = QtGui.QDateTimeEdit(self.groupBox)
        self.dtPicker.setReadOnly(True)
        self.dtPicker.setCalendarPopup(True)
        self.dtPicker.setObjectName(_fromUtf8("dtPicker"))
        self.gridLayout_3.addWidget(self.dtPicker, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 3, 1, 1)
        self.stConcepts = QtGui.QStackedWidget(self.groupBox)
        self.stConcepts.setObjectName(_fromUtf8("stConcepts"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.page_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.txtConcept = QtGui.QLineEdit(self.page_3)
        self.txtConcept.setAlignment(QtCore.Qt.AlignCenter)
        self.txtConcept.setReadOnly(True)
        self.txtConcept.setObjectName(_fromUtf8("txtConcept"))
        self.horizontalLayout.addWidget(self.txtConcept)
        self.stConcepts.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page_4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cbConcepts = QtGui.QComboBox(self.page_4)
        self.cbConcepts.setEnabled(False)
        self.cbConcepts.setObjectName(_fromUtf8("cbConcepts"))
        self.horizontalLayout_2.addWidget(self.cbConcepts)
        self.stConcepts.addWidget(self.page_4)
        self.gridLayout_3.addWidget(self.stConcepts, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.tableDetails = QtGui.QTableView(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableDetails.sizePolicy().hasHeightForWidth())
        self.tableDetails.setSizePolicy(sizePolicy)
        self.tableDetails.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableDetails.setAlternatingRowColors(True)
        self.tableDetails.setObjectName(_fromUtf8("tableDetails"))
        self.verticalLayout.addWidget(self.tableDetails)
        self.horizontalLayout_3.addWidget(self.splitter)
        frmOperations.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(frmOperations)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        frmOperations.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionNuevo = QtGui.QAction(frmOperations)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/document-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNuevo.setIcon(icon)
        self.actionNuevo.setObjectName(_fromUtf8("actionNuevo"))
        self.actionGuardar = QtGui.QAction(frmOperations)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/document-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardar.setIcon(icon1)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionCancelar = QtGui.QAction(frmOperations)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/dialog-cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCancelar.setIcon(icon2)
        self.actionCancelar.setObjectName(_fromUtf8("actionCancelar"))
        self.toolBar.addAction(self.actionNuevo)
        self.toolBar.addAction(self.actionGuardar)
        self.toolBar.addAction(self.actionCancelar)
        self.label_4.setBuddy(self.txtSearch)
        self.label.setBuddy(self.dtPicker)
        self.label_3.setBuddy(self.cbConcepts)

        self.retranslateUi(frmOperations)
        self.stConcepts.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmOperations)

    def retranslateUi(self, frmOperations):
        frmOperations.setWindowTitle(QtGui.QApplication.translate("frmOperations", "Ajustes Contables", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("frmOperations", "&Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmOperations", "Detalles", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmOperations", "&Fecha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmOperations", "Concepto", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("frmOperations", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevo.setText(QtGui.QApplication.translate("frmOperations", "nuevo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevo.setToolTip(QtGui.QApplication.translate("frmOperations", "Crear nuevo Ajuste Contable", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardar.setText(QtGui.QApplication.translate("frmOperations", "guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCancelar.setText(QtGui.QApplication.translate("frmOperations", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
