# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/windows/C/workspace/EsquipulasPy/esquipulaspy/ui/recibo.ui'
#
# Created by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmRecibo(object):
    def setupUi(self, frmRecibo):
        frmRecibo.setObjectName("frmRecibo")
        frmRecibo.resize(698, 630)
        self.centralwidget = QtGui.QWidget(frmRecibo)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tabdetails = QtGui.QWidget()
        self.tabdetails.setObjectName("tabdetails")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabdetails)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtGui.QGroupBox(self.tabdetails)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 130))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lblnrec = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblnrec.sizePolicy().hasHeightForWidth())
        self.lblnrec.setSizePolicy(sizePolicy)
        self.lblnrec.setStyleSheet("border:1px solid #000")
        self.lblnrec.setAlignment(QtCore.Qt.AlignCenter)
        self.lblnrec.setObjectName("lblnrec")
        self.gridLayout_2.addWidget(self.lblnrec, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.lblnreten = QtGui.QLabel(self.groupBox_4)
        self.lblnreten.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblnreten.sizePolicy().hasHeightForWidth())
        self.lblnreten.setSizePolicy(sizePolicy)
        self.lblnreten.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lblnreten.setStyleSheet("border:1px solid #000")
        self.lblnreten.setAlignment(QtCore.Qt.AlignCenter)
        self.lblnreten.setObjectName("lblnreten")
        self.gridLayout_2.addWidget(self.lblnreten, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 5, 1, 1)
        self.dtPicker = QtGui.QDateTimeEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtPicker.sizePolicy().hasHeightForWidth())
        self.dtPicker.setSizePolicy(sizePolicy)
        self.dtPicker.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dtPicker.setReadOnly(True)
        self.dtPicker.setCalendarPopup(True)
        self.dtPicker.setObjectName("dtPicker")
        self.gridLayout_2.addWidget(self.dtPicker, 0, 6, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.swcliente = QtGui.QStackedWidget(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swcliente.sizePolicy().hasHeightForWidth())
        self.swcliente.setSizePolicy(sizePolicy)
        self.swcliente.setStyleSheet("padding:0px;")
        self.swcliente.setObjectName("swcliente")
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName("page_7")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.page_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbcliente = QtGui.QComboBox(self.page_7)
        self.cbcliente.setMinimumSize(QtCore.QSize(0, 20))
        self.cbcliente.setEditable(True)
        self.cbcliente.setObjectName("cbcliente")
        self.horizontalLayout_6.addWidget(self.cbcliente)
        self.swcliente.addWidget(self.page_7)
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName("page_8")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.page_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtcliente = QtGui.QLineEdit(self.page_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtcliente.sizePolicy().hasHeightForWidth())
        self.txtcliente.setSizePolicy(sizePolicy)
        self.txtcliente.setMinimumSize(QtCore.QSize(0, 20))
        self.txtcliente.setStyleSheet("padding:0px;")
        self.txtcliente.setDragEnabled(True)
        self.txtcliente.setReadOnly(True)
        self.txtcliente.setObjectName("txtcliente")
        self.horizontalLayout_3.addWidget(self.txtcliente)
        self.swcliente.addWidget(self.page_8)
        self.gridLayout_2.addWidget(self.swcliente, 1, 1, 1, 6)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.swconcepto = QtGui.QStackedWidget(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swconcepto.sizePolicy().hasHeightForWidth())
        self.swconcepto.setSizePolicy(sizePolicy)
        self.swconcepto.setMaximumSize(QtCore.QSize(16777215, 30))
        self.swconcepto.setObjectName("swconcepto")
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbconcepto = QtGui.QComboBox(self.page_5)
        self.cbconcepto.setMinimumSize(QtCore.QSize(0, 20))
        self.cbconcepto.setEditable(True)
        self.cbconcepto.setObjectName("cbconcepto")
        self.verticalLayout_4.addWidget(self.cbconcepto)
        self.swconcepto.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtconcepto = QtGui.QLineEdit(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtconcepto.sizePolicy().hasHeightForWidth())
        self.txtconcepto.setSizePolicy(sizePolicy)
        self.txtconcepto.setMinimumSize(QtCore.QSize(0, 20))
        self.txtconcepto.setStyleSheet("None")
        self.txtconcepto.setDragEnabled(True)
        self.txtconcepto.setReadOnly(True)
        self.txtconcepto.setObjectName("txtconcepto")
        self.horizontalLayout_2.addWidget(self.txtconcepto)
        self.swconcepto.addWidget(self.page_6)
        self.gridLayout_2.addWidget(self.swconcepto, 2, 1, 1, 4)
        self.ckretener = QtGui.QCheckBox(self.groupBox_4)
        self.ckretener.setEnabled(False)
        self.ckretener.setChecked(True)
        self.ckretener.setObjectName("ckretener")
        self.gridLayout_2.addWidget(self.ckretener, 2, 5, 1, 1)
        self.swtasaret = QtGui.QStackedWidget(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swtasaret.sizePolicy().hasHeightForWidth())
        self.swtasaret.setSizePolicy(sizePolicy)
        self.swtasaret.setMaximumSize(QtCore.QSize(80, 50))
        self.swtasaret.setObjectName("swtasaret")
        self.page_9 = QtGui.QWidget()
        self.page_9.setObjectName("page_9")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.page_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cbtasaret = QtGui.QComboBox(self.page_9)
        self.cbtasaret.setEnabled(False)
        self.cbtasaret.setMinimumSize(QtCore.QSize(0, 20))
        self.cbtasaret.setEditable(False)
        self.cbtasaret.setObjectName("cbtasaret")
        self.horizontalLayout_9.addWidget(self.cbtasaret)
        self.label_8 = QtGui.QLabel(self.page_9)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.swtasaret.addWidget(self.page_9)
        self.page_10 = QtGui.QWidget()
        self.page_10.setObjectName("page_10")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.page_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.txttasaret = QtGui.QLineEdit(self.page_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txttasaret.sizePolicy().hasHeightForWidth())
        self.txttasaret.setSizePolicy(sizePolicy)
        self.txttasaret.setMinimumSize(QtCore.QSize(0, 20))
        self.txttasaret.setStyleSheet("None")
        self.txttasaret.setText("")
        self.txttasaret.setAlignment(QtCore.Qt.AlignCenter)
        self.txttasaret.setDragEnabled(True)
        self.txttasaret.setReadOnly(True)
        self.txttasaret.setObjectName("txttasaret")
        self.horizontalLayout_10.addWidget(self.txttasaret)
        self.swtasaret.addWidget(self.page_10)
        self.gridLayout_2.addWidget(self.swtasaret, 2, 6, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.splitter_2 = QtGui.QSplitter(self.tabdetails)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_2 = QtGui.QGroupBox(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 140))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtGui.QSplitter(self.groupBox_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frbotones = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frbotones.sizePolicy().hasHeightForWidth())
        self.frbotones.setSizePolicy(sizePolicy)
        self.frbotones.setMinimumSize(QtCore.QSize(300, 100))
        self.frbotones.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frbotones.setStyleSheet("padding:0px;")
        self.frbotones.setFrameShape(QtGui.QFrame.NoFrame)
        self.frbotones.setFrameShadow(QtGui.QFrame.Raised)
        self.frbotones.setObjectName("frbotones")
        self.gridLayout = QtGui.QGridLayout(self.frbotones)
        self.gridLayout.setObjectName("gridLayout")
        self.btnaddall = QtGui.QPushButton(self.frbotones)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnaddall.sizePolicy().hasHeightForWidth())
        self.btnaddall.setSizePolicy(sizePolicy)
        self.btnaddall.setMinimumSize(QtCore.QSize(26, 16))
        self.btnaddall.setStyleSheet("background: url(:/icons/res/arrow-right-double.png) no-repeat;")
        self.btnaddall.setText("")
        self.btnaddall.setFlat(True)
        self.btnaddall.setObjectName("btnaddall")
        self.gridLayout.addWidget(self.btnaddall, 1, 1, 1, 1)
        self.tablefacturas = QtGui.QTableView(self.frbotones)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablefacturas.sizePolicy().hasHeightForWidth())
        self.tablefacturas.setSizePolicy(sizePolicy)
        self.tablefacturas.setMinimumSize(QtCore.QSize(0, 50))
        self.tablefacturas.setStyleSheet("padding:0px;")
        self.tablefacturas.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablefacturas.setObjectName("tablefacturas")
        self.gridLayout.addWidget(self.tablefacturas, 0, 0, 4, 1)
        self.btnadd = QtGui.QPushButton(self.frbotones)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnadd.sizePolicy().hasHeightForWidth())
        self.btnadd.setSizePolicy(sizePolicy)
        self.btnadd.setStyleSheet("background: url(:/icons/res/arrow-right.png) no-repeat;\n"
"")
        self.btnadd.setText("")
        self.btnadd.setFlat(True)
        self.btnadd.setObjectName("btnadd")
        self.gridLayout.addWidget(self.btnadd, 0, 1, 1, 1)
        self.btnremove = QtGui.QPushButton(self.frbotones)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnremove.sizePolicy().hasHeightForWidth())
        self.btnremove.setSizePolicy(sizePolicy)
        self.btnremove.setStyleSheet("background: url(:/icons/res/arrow-left.png) no-repeat;\n"
"")
        self.btnremove.setText("")
        self.btnremove.setFlat(True)
        self.btnremove.setObjectName("btnremove")
        self.gridLayout.addWidget(self.btnremove, 2, 1, 1, 1)
        self.btnremoveall = QtGui.QPushButton(self.frbotones)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnremoveall.sizePolicy().hasHeightForWidth())
        self.btnremoveall.setSizePolicy(sizePolicy)
        self.btnremoveall.setMinimumSize(QtCore.QSize(26, 18))
        self.btnremoveall.setStyleSheet("background: url(:/icons/res/arrow-left-double.png) no-repeat;\n"
"")
        self.btnremoveall.setText("")
        self.btnremoveall.setFlat(True)
        self.btnremoveall.setObjectName("btnremoveall")
        self.gridLayout.addWidget(self.btnremoveall, 3, 1, 1, 1)
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.tableabonos = QtGui.QTableView(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableabonos.sizePolicy().hasHeightForWidth())
        self.tableabonos.setSizePolicy(sizePolicy)
        self.tableabonos.setMinimumSize(QtCore.QSize(0, 50))
        self.tableabonos.setStyleSheet("padding:0px;")
        self.tableabonos.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableabonos.setObjectName("tableabonos")
        self.horizontalLayout_11.addWidget(self.tableabonos)
        self.verticalLayout_3.addWidget(self.splitter)
        self.groupBox_3 = QtGui.QGroupBox(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tabledetails = QtGui.QTableView(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabledetails.sizePolicy().hasHeightForWidth())
        self.tabledetails.setSizePolicy(sizePolicy)
        self.tabledetails.setMinimumSize(QtCore.QSize(0, 70))
        self.tabledetails.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabledetails.setObjectName("tabledetails")
        self.horizontalLayout_7.addWidget(self.tabledetails)
        self.verticalLayout.addWidget(self.splitter_2)
        self.label_22 = QtGui.QLabel(self.tabdetails)
        self.label_22.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.txtobservaciones = QtGui.QPlainTextEdit(self.tabdetails)
        self.txtobservaciones.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtobservaciones.sizePolicy().hasHeightForWidth())
        self.txtobservaciones.setSizePolicy(sizePolicy)
        self.txtobservaciones.setMaximumSize(QtCore.QSize(16777215, 50))
        self.txtobservaciones.setReadOnly(True)
        self.txtobservaciones.setObjectName("txtobservaciones")
        self.horizontalLayout_5.addWidget(self.txtobservaciones)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtGui.QLabel(self.tabdetails)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.lbltotal = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltotal.sizePolicy().hasHeightForWidth())
        self.lbltotal.setSizePolicy(sizePolicy)
        self.lbltotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbltotal.setObjectName("lbltotal")
        self.gridLayout_3.addWidget(self.lbltotal, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.tabdetails)
        self.label_19.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)
        self.lbltotalreten = QtGui.QLabel(self.tabdetails)
        self.lbltotalreten.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltotalreten.sizePolicy().hasHeightForWidth())
        self.lbltotalreten.setSizePolicy(sizePolicy)
        self.lbltotalreten.setMinimumSize(QtCore.QSize(0, 20))
        self.lbltotalreten.setStyleSheet("None")
        self.lbltotalreten.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbltotalreten.setObjectName("lbltotalreten")
        self.gridLayout_3.addWidget(self.lbltotalreten, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tabdetails)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 2, 1)
        self.lbltotalrecibo = QtGui.QLabel(self.tabdetails)
        self.lbltotalrecibo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbltotalrecibo.setObjectName("lbltotalrecibo")
        self.gridLayout_3.addWidget(self.lbltotalrecibo, 2, 1, 2, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/document-edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabdetails, icon, "")
        self.tabnavigation = QtGui.QWidget()
        self.tabnavigation.setObjectName("tabnavigation")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabnavigation)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tablenavigation = QtGui.QTableView(self.tabnavigation)
        self.tablenavigation.setAlternatingRowColors(True)
        self.tablenavigation.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablenavigation.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablenavigation.setObjectName("tablenavigation")
        self.tablenavigation.horizontalHeader().setStretchLastSection(True)
        self.tablenavigation.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tablenavigation)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtGui.QLabel(self.tabnavigation)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.txtSearch = QtGui.QLineEdit(self.tabnavigation)
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout.addWidget(self.txtSearch)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabnavigation, icon1, "")
        self.horizontalLayout_8.addWidget(self.tabWidget)
        frmRecibo.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(frmRecibo)
        self.statusbar.setObjectName("statusbar")
        frmRecibo.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(frmRecibo)
        self.toolBar.setObjectName("toolBar")
        frmRecibo.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.label_5.setBuddy(self.dtPicker)
        self.label_6.setBuddy(self.txtconcepto)
        self.label_4.setBuddy(self.txtSearch)

        self.retranslateUi(frmRecibo)
        self.tabWidget.setCurrentIndex(0)
        self.swcliente.setCurrentIndex(1)
        self.swconcepto.setCurrentIndex(1)
        self.swtasaret.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmRecibo)
        frmRecibo.setTabOrder(self.cbcliente, self.cbconcepto)
        frmRecibo.setTabOrder(self.cbconcepto, self.ckretener)
        frmRecibo.setTabOrder(self.ckretener, self.cbtasaret)
        frmRecibo.setTabOrder(self.cbtasaret, self.tablefacturas)
        frmRecibo.setTabOrder(self.tablefacturas, self.btnadd)
        frmRecibo.setTabOrder(self.btnadd, self.btnaddall)
        frmRecibo.setTabOrder(self.btnaddall, self.btnremove)
        frmRecibo.setTabOrder(self.btnremove, self.btnremoveall)
        frmRecibo.setTabOrder(self.btnremoveall, self.tableabonos)
        frmRecibo.setTabOrder(self.tableabonos, self.tabledetails)
        frmRecibo.setTabOrder(self.tabledetails, self.txtobservaciones)
        frmRecibo.setTabOrder(self.txtobservaciones, self.dtPicker)
        frmRecibo.setTabOrder(self.dtPicker, self.tabWidget)
        frmRecibo.setTabOrder(self.tabWidget, self.txtcliente)
        frmRecibo.setTabOrder(self.txtcliente, self.txtconcepto)
        frmRecibo.setTabOrder(self.txtconcepto, self.txttasaret)
        frmRecibo.setTabOrder(self.txttasaret, self.txtSearch)
        frmRecibo.setTabOrder(self.txtSearch, self.tablenavigation)

    def retranslateUi(self, frmRecibo):
        frmRecibo.setWindowTitle(QtGui.QApplication.translate("frmRecibo", "Recibo Oficial de Caja", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("frmRecibo", "Datos del Recibo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmRecibo", "<b>Recibo No.</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblnrec.setText(QtGui.QApplication.translate("frmRecibo", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("frmRecibo", "<b>Retención No.</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblnreten.setText(QtGui.QApplication.translate("frmRecibo", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("frmRecibo", "&<b>Fecha</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.dtPicker.setDisplayFormat(QtGui.QApplication.translate("frmRecibo", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmRecibo", "<b>Recibimos de:</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("frmRecibo", "<b>En concepto de:</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.ckretener.setText(QtGui.QApplication.translate("frmRecibo", "Retener", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("frmRecibo", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmRecibo", "Detalle de Abono a Facturas", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("frmRecibo", "Especifique los tipos de pagos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("frmRecibo", "<b>Observaciones </b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmRecibo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Total a pagar</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltotal.setText(QtGui.QApplication.translate("frmRecibo", "0.0000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("frmRecibo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">- Retención</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltotalreten.setText(QtGui.QApplication.translate("frmRecibo", "0.0000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("frmRecibo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Total Recibido</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltotalrecibo.setText(QtGui.QApplication.translate("frmRecibo", "0.0000", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabdetails), None)
        self.label_4.setText(QtGui.QApplication.translate("frmRecibo", "&Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabnavigation), None)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("frmRecibo", "toolBar", None, QtGui.QApplication.UnicodeUTF8))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    frmRecibo = QtGui.QMainWindow()
    ui = Ui_frmRecibo()
    ui.setupUi(frmRecibo)
    frmRecibo.show()
    sys.exit(app.exec_())

